### ISSUE TITLE
Indexing history objects does not undo last known operation when relogging and typing undo for the first time since the relog.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#207]
FastAsync dev 184
WorldEdit dev 3596
PaperSpigot (MC 1.10) dev 830

* Make a quick operation. (i.e. region select, //cut)
* Relog.
* Type //undo.

It does not undo the operation. States the following in order;
```Indexing 1 history ojects on disk, please wait.``` 
```Nothing left to undo.```
```Indexing complete. Took: 0098 seconds!```

If you type ```/undo``` again immediately afterwards, it properly undoes the last operation.

Same problem occurs when you have undone the operation, relog, then type //redo to have it cut the region again. It does not redo the operation.

```Indexing 1 history objects on disk, please wait.```
```Nothing left to redo.```
```Indexing complete. Took: 0.098 seconds!```

Yet if you type redo again, it does not work like typing undo again. States ```Nothing left to redo.``` when typing it a second time. You have to type undo (states undo successfully even though nothing changed), then redo again for it to work. 
```
clipboard:
  use-disk: false
  delete-after-days: 1
```
```
queue:
  # If no blocks from completed edits are queued, and if the global queue has more available 
  # chunks to place from still-processing edits than the target size setting, it will begin
  # placing available blocks from edits still in the preprocessing stage.
  target-size: 64
  # This should equal the number of processors you have
  parallel-threads: 8
  # The time in milliseconds that the global queue can be idle before it is forced to start
  # on edits which are still in the preprocessing stage.
  max-wait-ms: 1000
  # Increase or decrease queue intensity (0 = balance of performance / stability)
  # Should not need to change this.  Increasing it (positive value) too high 
  # will probably cause the server to freeze, and decreasing it (negative value)
  # may reduce load on the server but should not be necessary.
  extra-time-ms: 0
  # Discard edits which have been idle for a certain amount of time (ms) (e.g. a plugin creates
  # an EditSession but never does anything with it).
  discard-after-ms: 60000
  progress:
    # Display constant titles about the progress of a user's edit
    display: false
    # How often edit progress is displayed
    interval: 1
```
```
history:
  # Should history be saved on disk:
  #  - Frees up a lot of memory
  #  - Persists restarts
  #  - Unlimited undo
  #  - Enables the rollback command
  use-disk: true
  # Use a database to store disk storage summaries:
  #  - Faster lookups and rollback from disk
  use-database: true
  # Record history with dispatching:
  #  - Faster as it avoids duplicate block checks
  #  - Worse compression since dispatch order is different
  combine-stages: false
  # Higher compression reduces the size of history at the expense of CPU
  # 0 = Uncompressed byte array
  # 1 = 1 pass fast compressor (default)
  # 2 = 2 x fast
  # 3 = 3 x fast
  # 4 = 1 x medium, 1 x fast
  # 5 = 1 x medium, 2 x fast
  # 6 = 1 x medium, 3 x fast
  # 7 = 1 x high, 1 x medium, 1 x fast
  # 8 = 1 x high, 1 x medium, 2 x fast
  # 9 = 1 x high, 1 x medium, 3 x fast
  # NOTE: If using disk, do some compression as smaller files save faster
  compression-level: 1
  # The buffer size for compression:
  #  - Larger = better ratio but uses more upfront memory
  buffer-size: 531441
  # The maximum time in milliseconds to wait for a chunk to load for an edit.
  #  (50ms = 1 server tick, 0 = Fastest).
  #  The default value of 100 should be safe for most cases.
  # 
  # Actions which require loaded chunks (e.g. copy) which do not load in time
  #  will use the last chunk as filler, which may appear as bands of duplicated blocks.
  # Actions usually wait about 25-50ms for the chunk to load, more if the server is lagging.
  # A value of 100ms does not force it to wait 100ms if the chunk loads in 10ms.
  # 
  # This value is a timeout in case a chunk is never going to load (for whatever odd reason).
  # If the action times out, the operation continues by using the previous chunk as filler,
  #  and displaying an error message.  In this case, either copy a smaller section,
  #  or increase chunk-wait-ms.
  # A value of 0 is faster simply because it doesn't bother loading the chunks or waiting.
  chunk-wait-ms: 100
  # Delete history on disk after a number of days
  delete-after-days: 7
  # Delete history in memory on logout (does not effect disk)
  delete-on-logout: true
  # If history should be enabled by default for plugins using WorldEdit:
  #  - It is faster to have disabled
  #  - Use of the FAWE API will not be effected
  enable-for-console: false
```
