### ISSUE TITLE
Check limit not resetting when using the same brush repeatedly.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#215]
FastAsync dev 184
WorldEdit dev 3596
PaperSpigot (MC 1.10) dev 830

@boy0001 Got a report from a player that after using a WE brush for a while, it stops working saying "your worldedit action was cancelled: too many block checks." Specifically using `//brush sphere stone 15` with a mask of obsidian,netherbrick,wool.

Is the check limit not resetting every time the brush is used? As in the limit isn't the maximum number of changes / operation size per time it is used? Creating a new (different) brush seemed to have reset the limit. In other words, not allowing the same brush to be used for more than 10 million changes?

```
# Generic tick limiter (not necessarily WorldEdit related, but still useful)
tick-limiter:
  # Max physics per tick
  physics: 500000
  # Max item spawns per tick
  items: 500000
```

```
limits:
  default:
    # Max number of block changes (e.g. by `//set stone`).
    max-changes: 10000000
    # Max number of blocks checked (e.g. `//count stone` which doesn't change blocks)
    max-checks: 10000000
    # Number of times a change can fail (e.g. if the player can't access that region)
    max-fails: 10000000
    # Allowed brush iterations (e.g. `//brush smooth`)
    max-iterations: 1000
    # Max allowed entities (e.g. cows)
    max-entities: 1337
    # Blockstates include Banner, Beacon, BrewingStand, Chest, CommandBlock, 
    # CreatureSpawner, Dispenser, Dropper, EndGateway, Furnace, Hopper, Jukebox, 
    # NoteBlock, Sign, Skull, Structure
    max-blockstates: 1337
    # Maximum size of the player's history in Megabytes
    max-history-mb: 150
```
