### ISSUE TITLE
Redstone Circuitry behaving weirdly with Fawe.

### ISSUE THREAD

**Issue by GoadingGoat** [boy0001/FastAsyncWorldedit#272]
Using Spigot 1.10.2 and Fawe bukkit110.

Redstone signals don't appear to be updating as they should.

Circuitry should look like picture below this once button has been pressed.

![2016-08-31_18 39 12](https://cloud.githubusercontent.com/assets/11308755/18118657/57b2153e-6faa-11e6-93bc-18513f8915d6.png)

Instead the comparators stay turned on but at very low power, causing the repeaters to amplify the signal.
see pic below
![2016-08-31_18 38 08](https://cloud.githubusercontent.com/assets/11308755/18118693/97f785b6-6faa-11e6-8d74-a97c131e9ad6.png)

**Comment by GoadingGoat** [comment]
here is a schematic of the farm, so you might be able to reproduce the bug.
[SimplePumpkinFarmSchem.zip](https://github.com/boy0001/FastAsyncWorldedit/files/446542/SimplePumpkinFarmSchem.zip)

**Comment by boy0001** [comment]
I need a `/fawe debugpaste`

**Comment by GoadingGoat** [comment]
I don't have it installed

**Comment by GoadingGoat** [comment]
http://hastebin.com/pudolanuzo

**Comment by boy0001** [comment]
Line 46 of your config, raise max-physics to 50000:
```YML
# Generic tick limiter (not necessarily WorldEdit related, but still useful)
tick-limiter:
  # Max physics per tick
  physics: 50000
  # Max item spawns per tick
  items: 1337
```
