### ISSUE TITLE
Tick limiter is causing items to despawn when breaking a chest.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#371]
FAWE dev 421 (http://ci.athion.net/job/FastAsyncWorldEdit/421/)

With the tick limiter enabled, breaking a chest full of items causes the items to immediately despawn - resulting in loss of items. i.e. breaking a chest full of dirt. Disabling the tick limiter, all is well.

```
# Generic tick limiter (not necessarily WorldEdit related, but useful to stop abuse)
tick-limiter:
  # Enable the limiter
  enabled: true
  # The interval in ticks
  interval: 1
  # Max falling blocks per interval (per chunk)
  falling: 512
  # Max physics per interval (per chunk)
  physics: 512
  # Max item spawns per interval (per chunk)
  items: 48
```
