### ISSUE TITLE
WorldEdit tips for cut, paste, and regen still showing despite being toggled off.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#389]
FastAsyncWorldEdit dev 484 (455 on jenkins)
FastAsyncVoxelSniper dev 484 (455 on jenkins)
WorldEdit dev 3674
VoxelSniper 5.171.0-SNAPSHOT
Paper dev 1026 (Spigot 1.11.2)

The WorldEdit tips for cut, paste, and regen commands still show up despite the tip permission being negated, set to false in the plugin.yml, and toggled off via the ```/tips``` command. Might have something to do with those tips not being in the ```tips:``` language section?

```
  cut:
    command_cut_slow: |-
      %s0 blocks were cut.
      Tip: lazycut is safer
    command_cut_lazy: '%s0 blocks will be removed on paste'
  paste:
    command_paste: |-
      The clipboard has been pasted at %s0
      Tip: Paste on click with &c//br copypaste
  regen:
    command_regen_0: |-
      Region regenerated.
      Tip: Use a biome with /regen [biome]
    command_regen_1: |-
      Region regenerated.
      Tip: Use a seed with /regen [biome] [seed]
    command_regen_2: Region regenerated.
```
