### ISSUE TITLE
Regen message tips not in tips section.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#395]
```
  regen:
    command_regen_0: |-
      Region regenerated.
      Tip: Use a biome with /regen [biome]
    command_regen_1: |-
      Region regenerated.
      Tip: Use a seed with /regen [biome] [seed]
```
