### ISSUE TITLE
Lighting bugs with WorldEdit

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#436]
FastAsyncWorldEdit dev 520
WorldEdit dev 3677
Paper dev 1060

When a schematic is pasted, there is quite a few lighting issues leading to black spots everywhere. Removing FAWE, worldedit pastes with correct lighting.

```
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: false
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 2
```
![link](http://i.imgur.com/tvSvqJu.jpg)

### Added from #457
> ![2017-03-07_16 31 38](https://cloud.githubusercontent.com/assets/10080017/23666779/dd713a14-0353-11e7-9c80-258e144cf93e.png)
seems to be a thing in other large WEs requiring lighting changes also

**Comment by dordsor21** [comment]
possibly related to #457

**Comment by dordsor21** [comment]
It might not be a duplicate as the lighting issues shown in #457 are regular and repeating, whereas this is random

**Comment by boy0001** [comment]
@dordsor21 
It's a slightly different symptom, but probably the same bad lighting code causing it. I've added the screenshot from your ticket to the description above.

**Comment by dordsor21** [comment]
Fair enough

**Comment by mibby** [comment]
FAWE v17.04.19-92fef6f-646-12.3.11
WorldEdit dev 3682
Paper dev 1082 (Spigot 1.11.2)

```
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: true
  async: true
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 1

```
@boy0001 Lighting in FAWE is still royally broken. Seeing that this ticket is open, I'll post details here instead of https://github.com/boy0001/FastAsyncWorldedit/issues/318.

![link5](https://i.gyazo.com/1a209d68545f133849a8a8a45aeef855.jpg)
* Player was fixing trees in the area by making region selections and typing ```//forest```.
* The area rendered on the live map (dynmap) went full bright and lost its biome coloring. This expanded the more he worldedited.
* Manually breaking / placing blocks in another area does not cause this oddity. Only breaks the live map chunk renders in areas people have worldedited.

Before
![link6](https://i.gyazo.com/95ee71fcbdc8a48bef2f9aac28dc771c.jpg)
After
![link7](https://i.gyazo.com/efaf32d3371d160ded9a87f09c63c8d4.png)

---

https://i.gyazo.com/e968a674d252cbe46044254b954033f3.mp4
* Player made an air selection region //cut above some blocks. Lighting went black.
(Some lighting fixed itself over time in-between videos.)
https://i.gyazo.com/7268967321f7f2ea5f4c607448f25035.mp4
* Player tried fixing the lighting within the region selection with ```//fixlighting```
* Everything went black.
https://gyazo.com/2d75c0b0c95d1011b95cc72e6f529168
* Player deselected his region and tried fixlighting again.

---

https://i.gyazo.com/f5dc67e6262bb9f232c54faab631f21d.mp4
* Broken lighting pockets when carving out with a brush.

---
![link10](https://i.gyazo.com/d40cf206ff63f4ba70e6a44ca1e46616.png)
* Player made a cube above water.
* Lighting under cube was broken.
* Player tried //fixlighting, didn't fix anything.
* Player tried //removelighting, then //fixlighting (in case it isn't recursive), didn't fix the zigzags.

---

![link11](https://i.gyazo.com/3fa8c8b07e6d3583d00497240e42a99d.jpg)
* Player went to a random beach that was fine. Then typed //fixlighting.
* It broke lighting.

**Comment by boy0001** [comment]
Not trying to detract from the obvious issues, but black surfaces in the image above are client side (it's an issue with how I send the chunk when it's already visible by the client). A relog would fix.

Specifically when the blocks are the top of the current chunk section, and the section above is empty. So at `y=15`, `y=31`, `y=47` etc.

I can revert to how it sent packets before where it didn't send the empty sections, but that had issues with ghost sections when removing blocks. A better solution is needed.

**Comment by mibby** [comment]
Light bugs still present as of FAWE dev 707. Player placed 2 sea lanterns down manually, then makes a layer with worldedit above it. Light seeps through the stone layer on top. As if it isn't doing re-light calculations or block updates to force it to check lighting levels again. Just plopping down blocks on top of the light and allowing it to seep through.

```
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: true
  async: true
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 1
```

Tested with both mode 1 and 2.
