### ISSUE TITLE
Limits

### ISSUE THREAD

**Issue by AndGK** [boy0001/FastAsyncWorldedit#597]
How can I remove the limits for the following section?

```
tick-limiter:
  # Enable the limiter
  enabled: false
  # The interval in ticks
  interval: 1
  # Max falling blocks per interval (per chunk)
  falling: 512
  # Max physics per interval (per chunk)
  physics: 512
  # Max item spawns per interval (per chunk)
  items: 10000
```
