### ISSUE TITLE
[Idea] Graphic display of loadable brushes in a custom inventory

### ISSUE THREAD

**Issue by Panossa** [boy0001/FastAsyncWorldedit#703]
**Description:**
Maybe add a custom inventory where you can click on different blocks/items which represent a loabable brush each. Config looks e.g. like this:
```
brushes:
  stonesphere:
    display-item: stone
    command: /br sphere 1
  other
    display-item: wooden_hoe
    command: /br ...
```
