### ISSUE TITLE
Concurrent Modification Exception

### ISSUE THREAD

**Issue by Miclebrick** [boy0001/FastAsyncWorldedit#823]
# Bug report
Sometimes lighting with async enabled causes concurrent modification exceptions, and even more rarely they cause crashes.
http://prntscr.com/hogp8h Error

Config:
```YML
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: true
  async: true
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 2
  ```
