### ISSUE TITLE
VoxelSniper operations are not being written to history / can't be undone with /u.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#855]
Paper dev 1290 (Spigot 1.12.2)
WorldEdit dev 3721 (6.1.9-SNAPSHOT)
VoxelSniper 5.172.0-SNAPSHOT
FAWE 17.12.30-5583994-953-18.0.10
FAVS 17.12.30-5583994-953-18.0.10

Player made a voxel operation, typed ```/u``` to undo it, and it undid a worldedit operation he made 15 minutes ago instead. He is not able to use ```/undo``` | ```/u``` to undo _any_ voxelsniper operations, only worldedit ones.

> Last month : use /b t redwood -> make a tree -> do /u -> tree gone.
Today : use /b t redwood -> make a tree -> do /u -> last worldedit operation undone

> so I just tried again, I did a //pos1 and //pos2 , //replace air stone (making a flat floor in the air), then I did a /b b and /v stone, then used the arrow in the middle of that floor. The ball appeared as normal, then did /u and the floor done with WE vanished, leaving the ball there.

```
clipboard:
  use-disk: true
  compression-level: 1
  delete-after-days: 1
history:
  use-disk: true
  use-database: true
  combine-stages: true
  compression-level: 3
  buffer-size: 531441
  chunk-wait-ms: 1000
  delete-after-days: 7
  delete-on-logout: true
  enable-for-console: false
  store-redo: true
  small-edits: false
```
