### ISSUE TITLE
FastAsyncWorldEdit is stripping lighting information from chunks with any worldedit operation in the area.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#931]
Paper dev 1337 (Spigot 1.12.2)
WorldEdit dev 3732
VoxelSniper 5.172.0-SNAPSHOT
FastAsyncWorldEdit dev 1016
FastAsyncVoxelSniper dev 1016

@boy0001 FastAsyncWorldEdit is stripping lighting information from chunks when doing _any_ worldedit operation in the area. This is causing world map renders such as dynmap to render chunks without lighting information after a worldedit operation.

* I have an already fully rendered map with dynmap.
* Player teleported to an area that rendered fine.
* Player _re-rendered_ the area with ```/dynmap radiusrender 100```
* No render tiles changed since nothing in the area changed. It re-rendered exactly the same with the smooth lighting.
![link](https://i.imgur.com/0G6Jpkl.png)

---

* In the same area, I had the player type the following worldedit commands.
* ```//desel```, then ```//fixlighting``` to regenerate lighting information in loaded chunks around the player.
* After the worldedit operation, I had the player re-render the tiles in the area with ```/dynmap radiusrender 100```.
* Tiles updated and all lighting information got stripped from the render area.
![link2](https://i.imgur.com/HuNZ0IY.png)

**This also happens when pasting in schematics and using other worldedit operations.**

Is there any way to fix this so FAWE doesn't break chunk lighting information and any way to fix chunks already damaged by this to re-render with proper lighting again?

```
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: false
  async: false
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 2
  # If existing lighting should be removed before relighting
  remove-first: false
```
